config/routes.rb
Rails.application.routes.draw do
  root 'moods#index'
  resources :tempos
  resources :colors
  resources :scales
  resources :modes
  resources :photos
  resources :moods

end

app/models/color.rb
class Color < ActiveRecord::Base
  has_many :moods, as: :moodable
end

app/models/mood.rb
class Mood < ActiveRecord::Base
  belongs_to :primary_mood, class_name: "Mood"
  has_many :secondary_moods, class_name: "Mood", foreign_key: "primary_mood_id"

  def related_moods
    Mood.where(primary_mood: self.primary_mood)
  end

  def scales
     Scale.where(primary_mood_id = self.id)
  end
end

app/models/scale.rb
class Scale < ActiveRecord::Base
  has_many :moods, as: :moodable
  belongs_to :mood, foreign_key: "primary_mood_id"
  belongs_to :mood, foreign_key: "secondary_mood_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController
  before_action :set_mood, only: [:show, :edit, :update, :destroy]

  # GET /moods
  # GET /moods.json
  def index
    @moods = Mood.all
  end

  # GET /moods/1
  # GET /moods/1.json
  def show
    
  end

  # GET /moods/new
  def new
    @mood = Mood.new
  end

  # GET /moods/1/edit
  def edit
  end

  # POST /moods
  # POST /moods.json
  def create
    @mood = Mood.new(mood_params)

    respond_to do |format|
      if @mood.save
        format.html { redirect_to @mood, notice: 'Mood was successfully created.' }
        format.json { render :show, status: :created, location: @mood }
      else
        format.html { render :new }
        format.json { render json: @mood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moods/1
  # PATCH/PUT /moods/1.json
  def update
    respond_to do |format|
      if @mood.update(mood_params)
        format.html { redirect_to @mood, notice: 'Mood was successfully updated.' }
        format.json { render :show, status: :ok, location: @mood }
      else
        format.html { render :edit }
        format.json { render json: @mood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moods/1
  # DELETE /moods/1.json
  def destroy
    @mood.destroy
    respond_to do |format|
      format.html { redirect_to moods_url, notice: 'Mood was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mood
      @mood = Mood.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mood_params
      params.require(:mood).permit(:name, :description, :image_url, :primary_mood_id)
    end
end

app/controllers/scales_controller.rb
class ScalesController < ApplicationController
  before_action :set_scale, only: [:show, :edit, :update, :destroy]

  # GET /scales
  # GET /scales.json
  def index
    @scales = Scale.all
  end

  # GET /scales/1
  # GET /scales/1.json
  def show
  end

  # GET /scales/new
  def new
    @scale = Scale.new
  end

  # GET /scales/1/edit
  def edit
  end

  # POST /scales
  # POST /scales.json
  def create
    @scale = Scale.new(scale_params)

    respond_to do |format|
      if @scale.save
        format.html { redirect_to @scale, notice: 'Scale was successfully created.' }
        format.json { render :show, status: :created, location: @scale }
      else
        format.html { render :new }
        format.json { render json: @scale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scales/1
  # PATCH/PUT /scales/1.json
  def update
    respond_to do |format|
      if @scale.update(scale_params)
        format.html { redirect_to @scale, notice: 'Scale was successfully updated.' }
        format.json { render :show, status: :ok, location: @scale }
      else
        format.html { render :edit }
        format.json { render json: @scale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scales/1
  # DELETE /scales/1.json
  def destroy
    @scale.destroy
    respond_to do |format|
      format.html { redirect_to scales_url, notice: 'Scale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scale
      @scale = Scale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scale_params
      params.require(:scale).permit(:name, :description, :audio_url, :image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/modes_helper.rb
module ModesHelper
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/scales_helper.rb
module ScalesHelper
end

app/helpers/tempos_helper.rb
module TemposHelper
end

app/views/colors/_form.html.erb
<%= form_for(@color) do |f| %>
  <% if @color.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@color.errors.count, "error") %> prohibited this color from being saved:</h2>

      <ul>
      <% @color.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :hex_code %><br>
    <%= f.text_field :hex_code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/colors/edit.html.erb
<h1>Editing Color</h1>

<%= render 'form' %>

<%= link_to 'Show', @color %> |
<%= link_to 'Back', colors_path %>

app/views/colors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Colors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Hex code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colors.each do |color| %>
      <tr>
        <td><%= color.name %></td>
        <td><%= color.hex_code %></td>
        <td><%= link_to 'Show', color %></td>
        <td><%= link_to 'Edit', edit_color_path(color) %></td>
        <td><%= link_to 'Destroy', color, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Color', new_color_path %>

app/views/colors/new.html.erb
<h1>New Color</h1>

<%= render 'form' %>

<%= link_to 'Back', colors_path %>

app/views/colors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @color.name %>
</p>

<p>
  <strong>Hex code:</strong>
  <%= @color.hex_code %>
</p>

<%= link_to 'Edit', edit_color_path(@color) %> |
<%= link_to 'Back', colors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MoodDictionary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/modes/_form.html.erb
<%= form_for(@mode) do |f| %>
  <% if @mode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mode.errors.count, "error") %> prohibited this mode from being saved:</h2>

      <ul>
      <% @mode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/modes/edit.html.erb
<h1>Editing Mode</h1>

<%= render 'form' %>

<%= link_to 'Show', @mode %> |
<%= link_to 'Back', modes_path %>

app/views/modes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Modes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @modes.each do |mode| %>
      <tr>
        <td><%= mode.name %></td>
        <td><%= mode.description %></td>
        <td><%= mode.url %></td>
        <td><%= link_to 'Show', mode %></td>
        <td><%= link_to 'Edit', edit_mode_path(mode) %></td>
        <td><%= link_to 'Destroy', mode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mode', new_mode_path %>

app/views/modes/new.html.erb
<h1>New Mode</h1>

<%= render 'form' %>

<%= link_to 'Back', modes_path %>

app/views/modes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mode.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @mode.description %>
</p>

<p>
  <strong>Url:</strong>
  <%= @mode.url %>
</p>

<%= link_to 'Edit', edit_mode_path(@mode) %> |
<%= link_to 'Back', modes_path %>

app/views/moods/_form.html.erb
<%= form_for(@mood) do |f| %>
  <% if @mood.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mood.errors.count, "error") %> prohibited this mood from being saved:</h2>

      <ul>
      <% @mood.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_area :image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/moods/edit.html.erb
<h1>Editing Mood</h1>

<%= render 'form' %>

<%= link_to 'Show', @mood %> |
<%= link_to 'Back', moods_path %>

app/views/moods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mood Modes Dictionary</h1>
<%= audio_tag "http://soundbible.com/mp3/Red_stag_roar-Juan_Carlos_-2004708707.mp3", controls: true, autoplay: false %>

<div class="container">
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <div class="row">
   <% @moods.each do |mood| %>
<div class="col s12 m6 l3">
          <div class="card">
            <div class="card-image">
              <img src="<%= mood.image_url %>">
              <span class="card-title"><%= mood.name %></span>
            </div>
            <div class="card-content">
              <p><%= mood.description %></p>

            </div>
            <div class="card-action">
              <%= link_to 'I Feel Like This', mood %></a>
            </div>
          </div>
        </div>
    <% end %>
</div>

  <tbody>
    <% @moods.each do |mood| %>
      <tr>
        <td><%= mood.name %></td>
        <td><%= mood.description %></td>
        <td><%= mood.image_url %></td>
        <td><%= link_to 'Show', mood %></td>
        <td><%= link_to 'Edit', edit_mood_path(mood) %></td>
        <td><%= link_to 'Destroy', mood, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mood', new_mood_path %>

app/views/moods/new.html.erb
<h1>New Mood</h1>

<%= render 'form' %>

<%= link_to 'Back', moods_path %>

app/views/moods/show.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>

  <h2>
    <%= @mood.name %>
  </h2>

  <% @mood.scales.each do |scale| %>
    <h4><%= scale.name %></h4>
    <% if scale.image_url %>
      <img src=<%= scale.image_url %>>
    <% end %>
    <p><%= scale.description %>
    <h5>Chords </h5>
    <div class="row">
      <div class="col offset-s2 s1"><%= scale.i %></div>
      <div class="col s1"><%= scale.ii %></div>
      <div class="col s1"><%= scale.iii %></div>
      <div class="col s1"><%= scale.iv %></div>
      <div class="col s1"><%= scale.v %></div>
      <div class="col s1"><%= scale.vi %></div>
      <div class="col s1"><%= scale.vii %></div>
    </div>

  <% end %>

  <%= link_to 'Back', moods_path %>

</div>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mood Dictionary</h1>
<div class="container">
  <div class="row">
    <div class="s12 m4 l8">
    <%= audio_tag "https://upload.wikimedia.org/wikipedia/commons/b/b5/Dorian_mode_C.mid", controls: true, autoplay: false %>
    </div>
  </div>
<div class="row">
  <% @photos.each do |pic| %>
    <div class="col s12 m6 l3">
          <div class="card">
            <div class="card-image">
              <img src="<%= pic.url %>">
              <span class="card-title"><%= pic.name %></span>
            </div>
            <div class="card-content">
              <p>This is where related pic info will go</p>

            </div>
            <div class="card-action">
              <a href="#">I Feel Like This</a>
            </div>
          </div>
        </div>
    <% end %>
</div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th><%= link_to 'New Photo', new_photo_path %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
    <tr>
        <td><%= photo.name %></td>
        <td><%= photo.url %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @photo.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @photo.url %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/scales/_form.html.erb
<%= form_for(@scale) do |f| %>
  <% if @scale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scale.errors.count, "error") %> prohibited this scale from being saved:</h2>

      <ul>
      <% @scale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :audio_url %><br>
    <%= f.text_field :audio_url %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scales/edit.html.erb
<h1>Editing Scale</h1>

<%= render 'form' %>

<%= link_to 'Show', @scale %> |
<%= link_to 'Back', scales_path %>

app/views/scales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Scales</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Audio url</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scales.each do |scale| %>
      <tr>
        <td><%= scale.name %></td>
        <td><%= scale.description %></td>
        <td><%= scale.audio_url %></td>
        <td><%= scale.image_url %></td>
        <td><%= link_to 'Show', scale %></td>
        <td><%= link_to 'Edit', edit_scale_path(scale) %></td>
        <td><%= link_to 'Destroy', scale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scale', new_scale_path %>

app/views/scales/new.html.erb
<h1>New Scale</h1>

<%= render 'form' %>

<%= link_to 'Back', scales_path %>

app/views/scales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @scale.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @scale.description %>
</p>

<p>
  <strong>Audio url:</strong>
  <%= @scale.audio_url %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @scale.image_url %>
</p>

<%= link_to 'Edit', edit_scale_path(@scale) %> |
<%= link_to 'Back', scales_path %>

app/views/tempos/_form.html.erb
<%= form_for(@tempo) do |f| %>
  <% if @tempo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tempo.errors.count, "error") %> prohibited this tempo from being saved:</h2>

      <ul>
      <% @tempo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bpm %><br>
    <%= f.number_field :bpm %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tempos/edit.html.erb
<h1>Editing Tempo</h1>

<%= render 'form' %>

<%= link_to 'Show', @tempo %> |
<%= link_to 'Back', tempos_path %>

app/views/tempos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tempos</h1>

<table>
  <thead>
    <tr>
      <th>Bpm</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tempos.each do |tempo| %>
      <tr>
        <td><%= tempo.bpm %></td>
        <td><%= link_to 'Show', tempo %></td>
        <td><%= link_to 'Edit', edit_tempo_path(tempo) %></td>
        <td><%= link_to 'Destroy', tempo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tempo', new_tempo_path %>

app/views/tempos/new.html.erb
<h1>New Tempo</h1>

<%= render 'form' %>

<%= link_to 'Back', tempos_path %>

app/views/tempos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bpm:</strong>
  <%= @tempo.bpm %>
</p>

<%= link_to 'Edit', edit_tempo_path(@tempo) %> |
<%= link_to 'Back', tempos_path %>